import {TableInformation} from "../interfaces/table-interface";

export const TABLE_MOCK: TableInformation[]  = [
  {
    tableNumber: 1,
    state: false,
    mainUser: 'User 1',
    mainUserState: 'Student',
    requestedUser: 'User 2',
    requestedUserPosition: 'Student',
    dateOfBooking: '',
  },
  {
    tableNumber: 2,
    state: true,
    mainUser: 'User 3',
    mainUserState: 'Student',
    requestedUser: 'User 4',
    requestedUserPosition: 'Teacher',
    requestedUserState: 'ACCEPTED',
    dateOfBooking: '',
  },
  {
    tableNumber: 3,
    state: false,
    mainUser: 'User 5',
    mainUserState: 'Teacher',
    requestedUser: 'User 6',
    requestedUserPosition: 'Teacher',
    dateOfBooking: '',
  },
  {
    tableNumber: 4,
    state: true,
    mainUser: 'User 7',
    mainUserState: 'Student',
    requestedUser: 'User 8',
    requestedUserPosition: 'Student',
    requestedUserState: 'PENDING',
    dateOfBooking: '',
  },
  {
    tableNumber: 5,
    state: false,
    mainUser: 'User 9',
    mainUserState: 'Student',
    requestedUser: 'User 10',
    requestedUserPosition: 'Teacher',
    dateOfBooking: '',
  },
  {
    tableNumber: 6,
    state: false,
    mainUser: 'User 11',
    mainUserState: 'Teacher',
    requestedUser: 'User 12',
    requestedUserPosition: 'Teacher',
    dateOfBooking: '',
  },
  {
    tableNumber: 7,
    state: true,
    mainUser: 'User 13',
    mainUserState: 'Teacher',
    requestedUser: 'User 14',
    requestedUserPosition: 'Student',
    requestedUserState: 'ACCEPTED',
    dateOfBooking: '',
  },
  {
    tableNumber: 8,
    state: true,
    mainUser: 'User 15',
    mainUserState: 'Student',
    requestedUser: 'User 16',
    requestedUserPosition: 'Teacher',
    requestedUserState: 'PENDING',
    dateOfBooking: '',
  }

]
